# Generated by Django 4.2.6 on 2023-11-19 07:03

import blog.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='category_thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_slug', models.SlugField(max_length=100)),
                ('body', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, null=True, size=None)),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to=blog.models.Blog.path_for_blog_image)),
                ('desktop_image', models.ImageField(blank=True, null=True, upload_to=blog.models.Blog.path_for_blog_image)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('read_time', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.category')),
            ],
        ),
    ]
