# Generated by Django 4.2 on 2024-03-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_category_blog_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title_slug',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='short_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
