# Generated by Django 4.2 on 2024-03-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_title_slug_blog_slug_blog_short_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_editor_choice',
            field=models.BooleanField(default=False),
        ),
    ]
